# Generated by Django 5.2 on 2025-05-23 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('subject', models.CharField(choices=[('java_full_stack', 'Java Full Stack'), ('python_full_stack', 'Python Full Stack'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('pending', 'Pending'), ('dropout', 'Dropout')], default='pending', max_length=10)),
                ('enquiry_type', models.CharField(choices=[('someone_telephonic', 'Enquiry for Someone Telephonic'), ('direct_telephonic', 'Direct Enquiry Telephonic'), ('someone_walkin', 'Enquiry for Someone WalkIn'), ('direct_walkin', 'Direct Enquiry WalkIn'), ('telephonic_to_walkin', 'Telephonic To Walkin')], default='direct_telephonic', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('parent_number', models.CharField(blank=True, max_length=15, null=True)),
                ('target_fees', models.DecimalField(blank=True, decimal_places=2, help_text='Total fees for the course', max_digits=12, null=True)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid by the student', max_digits=12)),
                ('fees_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Remaining balance (calculated automatically)', max_digits=12, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Deadline for full fees payment', null=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiry.counsellor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='enquiry.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
