# Generated by Django 5.2 on 2025-05-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='name',
        ),
        migrations.AddField(
            model_name='counsellor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
