# Generated by Django 5.2 on 2025-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='followup_date',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
