# Generated by Django 5.2 on 2025-05-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_remove_comment_followup_date_enquiry_followup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('somme', 'Enquiry for Somme'), ('direct', 'Direct Enquiry')], default='direct', max_length=10),
        ),
    ]
