# Generated by Django 5.2 on 2025-05-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_remove_counsellor_name_counsellor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellor',
            name='user',
        ),
        migrations.AddField(
            model_name='counsellor',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
