# Generated by Django 5.2 on 2025-05-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('somme', 'Enquiry for Someone'), ('direct', 'Direct Enquiry')], default='direct', max_length=10),
        ),
    ]
