# Generated by Django 5.2 on 2025-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_remove_counsellor_user_counsellor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=150, unique=True)),
                ('college_place', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
