# Generated by Django 5.2 on 2025-05-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_collegeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='enquiry.collegeinfo'),
        ),
    ]
