# Generated by Django 5.2 on 2025-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_enquiry_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='native_district_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
