# Generated by Django 5.2 on 2025-05-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_alter_comment_options_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
