# Generated by Django 5.2 on 2025-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('someone', 'Enquiry for Someone'), ('direct', 'Direct Enquiry')], default='direct', max_length=10),
        ),
    ]
