# Generated by Django 5.2 on 2025-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_enquiry_native_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='visit_type',
            field=models.CharField(choices=[('alone_walkin', 'Alone Walkin'), ('came_with_parents', 'Came with parents'), ('student_reference', 'Student Reference'), ('old_student_reference', 'Old Student Reference'), ('came_with_relatives', 'Came with relatives')], default='alone_walkin', help_text='How did the student come for enquiry?', max_length=30),
        ),
    ]
