# Generated by Django 5.2 on 2025-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_enquiry_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='other_subject_name',
            field=models.CharField(blank=True, help_text="Specify the subject if 'Other' is selected", max_length=100, null=True),
        ),
    ]
