# Generated by Django 5.2 on 2025-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_enquiry_fees_paid_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField(default=2025)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Set the monthly fees collection target', max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Monthly Targets',
                'unique_together': {('month', 'year')},
            },
        ),
    ]
