# Generated by Django 5.2 on 2025-06-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_monthlytarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='college',
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate')], max_length=2)),
                ('ug_degree', models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('be', 'B.E'), ('bsc', 'B.Sc'), ('bca', 'BCA'), ('bcom', 'B.Com'), ('ba', 'B.A'), ('other', 'Other UG')], max_length=20, null=True)),
                ('other_ug_degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_degree', models.CharField(blank=True, choices=[('mtech', 'M.Tech'), ('mca', 'MCA'), ('mba', 'MBA'), ('msc', 'M.Sc'), ('ma', 'M.A'), ('other', 'Other PG')], max_length=20, null=True)),
                ('other_pg_degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name', models.CharField(max_length=200)),
                ('college_place', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, help_text='e.g. 78.50', max_digits=5)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='enquiry.enquiry')),
            ],
        ),
    ]
