# Generated by Django 5.2 on 2025-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0013_alter_enquiry_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_joined_batch',
            field=models.BooleanField(default=False, help_text='True if the student has joined a batch'),
        ),
    ]
