# Generated by Django 5.2 on 2025-06-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0014_enquiry_is_joined_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='joined_date',
            field=models.DateField(blank=True, help_text='Date when the student joined', null=True),
        ),
    ]
