# Generated by Django 5.2 on 2025-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0015_enquiry_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('joined', 'Joined'), ('pending', 'Pending'), ('dropout', 'Dropout'), ('joined_in_qspiders', 'Joined In Qspiders')], default='pending', max_length=30),
        ),
    ]
