# Generated by Django 5.2 on 2025-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0016_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('joined', 'Joined'), ('pending', 'Pending'), ('dropout', 'Dropout')], default='pending', max_length=10),
        ),
    ]
