# Generated by Django 5.2 on 2025-06-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0018_tracker_trainer_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiry.batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
