# Generated by Django 5.2 on 2025-06-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0019_enquiry_batch_alter_batch_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='tracker',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
