# Generated by Django 5.2 on 2025-06-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_remove_batch_tracker_remove_batch_trainer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='enquiry.counsellor'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='is_joined_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='other_subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='visit_type',
            field=models.CharField(choices=[('alone_walkin', 'Alone Walkin'), ('came_with_parents', 'Came with parents'), ('student_reference', 'Student Reference'), ('old_student_reference', 'Old Student Reference'), ('came_with_relatives', 'Came with relatives'), ('telephonic', 'Telephonic')], default='alone_walkin', max_length=30),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['enquiry'], name='enquiry_com_enquiry_bbd396_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='enquiry_com_created_6129b8_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['created_at'], name='enquiry_enq_created_e02c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['joined_date'], name='enquiry_enq_joined__e65c21_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['status'], name='enquiry_enq_status_38de8a_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['counsellor'], name='enquiry_enq_counsel_6782d1_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['enquiry_date'], name='enquiry_enq_enquiry_3457a4_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['enquiry_type'], name='enquiry_enq_enquiry_4a1d44_idx'),
        ),
    ]
