# Generated by Django 5.2 on 2025-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
